In [ ]:
# 1. caricare i dati del file in un dataframe Pandas
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
ilfile = pd.read_csv("/content/drive/MyDrive/2010.csv", sep=";") #sep=";"

Mounted at /content/drive

In [ ]:
ilfile[["Title","Genres"]][0:10]

,Title,Genres
0,127 Hours,Adventure|Biography|Drama|Thriller
1,3 Backyards,Drama
2,3,Comedy|Drama|Romance
3,8: The Mormon Proposition,Documentary
4,A Turtle's Tale: Sammy's Adventures,Adventure|Animation|Family
5,Alice in Wonderland,Adventure|Family|Fantasy
6,Alice in Wonderland,Adventure|Family|Fantasy
7,All Good Things,Crime|Drama|Mystery|Romance|Thriller
8,Alpha and Omega,Adventure|Animation|Comedy|Family|Romance
9,Amigo,Drama|War

In [ ]:
ilfile.iloc[0:10][["Title", "Genres"]]

,Title,Genres
0,127 Hours,Adventure|Biography|Drama|Thriller
1,3 Backyards,Drama
2,3,Comedy|Drama|Romance
3,8: The Mormon Proposition,Documentary
4,A Turtle's Tale: Sammy's Adventures,Adventure|Animation|Family
5,Alice in Wonderland,Adventure|Family|Fantasy
6,Alice in Wonderland,Adventure|Family|Fantasy
7,All Good Things,Crime|Drama|Mystery|Romance|Thriller
8,Alpha and Omega,Adventure|Animation|Comedy|Family|Romance
9,Amigo,Drama|War

In [ ]:
ilfile[(ilfile["Language"] == "English") & (ilfile["Country"] == "France")]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
4,A Turtle's Tale: Sammy's Adventures,2010.0,Adventure|Animation|Family,English,France,PG,88.0,"2,35",NaN,NaN,...,749.0,602.0,3874,0,2.0,5385,22.0,56.0,"6,1",NaN
59,From Paris with Love,2010.0,Action|Thriller,English,France,R,92.0,"2,35",52000000.0,23324666.0,...,135.0,75.0,488,0,1.0,97775,211.0,203.0,"6,5",NaN
64,Green Zone,2010.0,Action|Drama|Thriller|War,English,France,R,115.0,"2,35",100000000.0,35024475.0,...,537.0,95.0,13761,0,1.0,110364,261.0,266.0,"6,9",NaN
139,Rubber,2010.0,Comedy|Fantasy|Horror,English,France,R,82.0,"1,85",500000.0,98017.0,...,248.0,196.0,1498,46000,0.0,26185,170.0,230.0,"5,8",NaN
179,The Ghost Writer,2010.0,Mystery|Thriller,English,France,PG-13,128.0,"2,35",45000000.0,15523168.0,...,766.0,501.0,2507,15000,2.0,132423,349.0,343.0,"7,2",NaN
185,The Last Exorcism,2010.0,Drama|Horror|Thriller,English,France,PG-13,87.0,"1,85",1800000.0,40990055.0,...,400.0,308.0,1958,0,0.0,41509,300.0,311.0,"5,6",NaN
262,Carnage,2011.0,Comedy|Drama,English,France,R,80.0,"2,35",25000000.0,NaN,...,11000.0,132.0,25143,21000,3.0,96480,181.0,376.0,"7,2",NaN
266,Colombiana,2011.0,Action|Crime|Drama|Thriller,English,France,PG-13,112.0,"2,35",40000000.0,36665854.0,...,738.0,674.0,3432,15000,0.0,76498,203.0,201.0,"6,4",NaN
374,Silent House,2011.0,Drama|Horror|Mystery|Thriller,English,France,R,86.0,"1,85",2000000.0,12555230.0,...,44.0,32.0,218,0,0.0,18566,154.0,218.0,"5,3",NaN
391,The Artist,2011.0,Comedy|Drama|Romance,English,France,PG-13,100.0,"1,33",15000000.0,44667095.0,...,897.0,628.0,4606,30000,0.0,190030,583.0,576.0,8,NaN
432,Tinker Tailor Soldier Spy,2011.0,Drama|Mystery|Thriller,English,France,R,127.0,"2,35",20000000.0,24104113.0,...,14000.0,10000.0,46241,24000,1.0,149066,517.0,466.0,"7,1",NaN
543,Lockout,2012.0,Action|Adventure|Sci-Fi|Thriller,English,France,PG-13,95.0,"2,35",20000000.0,14291570.0,...,447.0,80.0,1414,10000,2.0,82082,236.0,289.0,"6,1",NaN
550,Maniac,2012.0,Horror|Thriller,English,France,Not Rated,89.0,"2,35",6000000.0,12843.0,...,378.0,118.0,1233,0,0.0,27297,131.0,279.0,"6,1",NaN
558,On the Road,2012.0,Adventure|Drama,English,France,R,137.0,"2,35",25000000.0,717753.0,...,10000.0,4000.0,33747,27000,4.0,33107,128.0,252.0,"6,1",NaN
588,Silent Hill: Revelation 3D,2012.0,Adventure|Drama|Horror|Mystery|Thriller,English,France,R,95.0,"2,35",20000000.0,17529157.0,...,494.0,206.0,2173,25000,0.0,49888,220.0,173.0,5,NaN
604,Taken 2,2012.0,Action|Crime|Thriller,English,France,PG-13,98.0,"2,35",45000000.0,139852971.0,...,935.0,558.0,16410,63000,0.0,238671,461.0,358.0,"6,3",NaN
715,Blood Ties,2013.0,Crime|Drama|Thriller,English,France,R,144.0,"2,35",25500000.0,41229.0,...,960.0,745.0,18442,0,6.0,14612,41.0,91.0,"6,5",NaN
872,The Last Exorcism Part II,2013.0,Drama|Horror|Thriller,English,France,PG-13,93.0,"2,35",5000000.0,15152879.0,...,541.0,400.0,46868,0,0.0,13506,68.0,161.0,4,NaN
891,The Young and Prodigious T.S. Spivet,2013.0,Action|Adventure|Drama|Family,English,France,PG,105.0,"2,35",33000000.0,99462.0,...,648.0,223.0,1843,5000,1.0,11347,28.0,122.0,"7,1",NaN
912,Zulu,2013.0,Crime|Drama|Thriller,English,France,R,110.0,"2,35",16000000.0,NaN,...,170.0,44.0,5273,0,0.0,12817,43.0,69.0,"6,7",NaN
955,Brick Mansions,2014.0,Action|Crime|Drama|Thriller,English,France,PG-13,100.0,"2,35",28000000.0,20285518.0,...,727.0,561.0,25387,0,2.0,32103,112.0,177.0,"5,7",NaN
983,Escobar: Paradise Lost,2014.0,Crime|Drama|Romance|Thriller,English,France,R,120.0,NaN,17000000.0,106869.0,...,287.0,55.0,14492,0,1.0,13762,39.0,106.0,"6,6",NaN
1037,Lucy,2014.0,Action|Sci-Fi|Thriller,English,France,R,89.0,"2,35",40000000.0,126546825.0,...,11000.0,903.0,32325,83000,0.0,327367,918.0,433.0,"6,4",NaN
1088,Taken 3,2014.0,Action|Thriller,English,France,PG-13,115.0,"2,35",48000000.0,89253340.0,...,794.0,482.0,16967,38000,0.0,133436,323.0,222.0,6,NaN
1152,United Passions,2014.0,Drama|History|Sport,English,France,Not Rated,110.0,"2,35",24000000.0,NaN,...,919.0,432.0,2725,0,4.0,3279,22.0,7.0,2,NaN
1162,Wolves,2014.0,Action|Horror,English,France,R,91.0,"2,35",18000000.0,NaN,...,918.0,413.0,13545,0,2.0,5693,34.0,59.0,"5,3",NaN
1186,Bizarre,2015.0,Drama|Musical|Romance,English,France,Unrated,98.0,"1,78",500000.0,NaN,...,0.0,0.0,19,114,0.0,569,1.0,9.0,"4,3",NaN
1345,The Little Prince,2015.0,Adventure|Animation|Drama|Family|Fantasy,English,France,PG,108.0,"2,35",81200000.0,1339152.0,...,11000.0,6000.0,30230,31000,1.0,28276,64.0,119.0,"7,8",NaN
1362,The Transporter Refueled,2015.0,Action|Crime|Thriller,English,France,PG-13,96.0,"2,35",25000000.0,16027866.0,...,173.0,150.0,1411,0,0.0,26767,121.0,148.0,"5,1",NaN
1482,The Neon Demon,2016.0,Horror|Thriller,English,France,R,118.0,"2,35",7000000.0,1330827.0,...,860.0,500.0,19879,0,2.0,9866,73.0,253.0,7,NaN
1484,The Purge: Election Year,2016.0,Action|Horror|Sci-Fi|Thriller,English,France,R,109.0,"2,35",10000000.0,78845130.0,...,465.0,393.0,2480,0,1.0,17596,94.0,165.0,"6,1",NaN
1509,Carlos,NaN,Biography|Crime|Drama|Thriller,English,France,Not Rated,334.0,"2,35",NaN,145118.0,...,30.0,30.0,1032,0,0.0,10111,36.0,108.0,"7,7",NaN

In [ ]:
ilfile[(ilfile["Genres"].str.contains("Drama")) & (ilfile["Genres"].str.contains("War"))]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
9,Amigo,2010.0,Drama|War,English,USA,R,124.0,NaN,1700000.0,183490.0,...,8.0,7.0,60,594,0.0,463,8.0,35.0,"5,8",NaN
16,Beneath Hill 60,2010.0,Drama|History|War,English,Australia,R,122.0,"2,35",9000000.0,NaN,...,109.0,59.0,498,0,12.0,5741,39.0,17.0,"7,1",NaN
28,Centurion,2010.0,Action|Adventure|Drama|History|Thriller|War,English,UK,R,97.0,"2,35",NaN,122288.0,...,794.0,570.0,15293,0,0.0,64777,201.0,195.0,"6,4",NaN
37,Dear John,2010.0,Drama|Romance|War,English,USA,PG-13,108.0,"2,35",25000000.0,80014842.0,...,861.0,690.0,19945,14000,NaN,104356,186.0,162.0,"6,3",NaN
64,Green Zone,2010.0,Action|Drama|Thriller|War,English,France,R,115.0,"2,35",100000000.0,35024475.0,...,537.0,95.0,13761,0,1.0,110364,261.0,266.0,"6,9",NaN
78,Incendies,2010.0,Drama|Mystery|War,French,Canada,R,139.0,"1,85",6800000.0,6857096.0,...,66.0,58.0,343,37000,0.0,80429,156.0,226.0,"8,2",NaN
142,Sarah's Key,2010.0,Drama|War,French,France,PG-13,111.0,"2,35",10000000.0,7691700.0,...,767.0,121.0,2140,0,2.0,12937,73.0,136.0,"7,5",NaN
230,1911,2011.0,Action|Adventure|Drama|History|War,Mandarin,China,R,121.0,"2,35",18000000.0,127437.0,...,643.0,187.0,1887,0,0.0,4670,27.0,63.0,6,NaN
232,5 Days of War,2011.0,Action|Drama|War,English,Georgia,R,113.0,"2,35",20000000.0,17149.0,...,111.0,18.0,708,0,9.0,12128,61.0,74.0,"5,6",NaN
268,Coriolanus,2011.0,Drama|Thriller|War,English,UK,R,123.0,"2,35",NaN,756452.0,...,451.0,131.0,18652,12000,0.0,27009,118.0,196.0,"6,2",NaN
284,Fort McCoy,2011.0,Drama|History|War,English,USA,R,100.0,NaN,3000000.0,73678.0,...,902.0,847.0,4374,348,1.0,266,8.0,8.0,"5,9",NaN
308,In the Land of Blood and Honey,2011.0,Drama|Romance|War,Bosnian,USA,R,127.0,"2,35",13000000.0,301305.0,...,164.0,116.0,796,0,0.0,31414,180.0,110.0,"4,3",NaN
402,The Flowers of War,2011.0,Drama|History|Romance|War,Mandarin,China,R,146.0,"2,35",94000000.0,9213.0,...,196.0,28.0,23240,13000,2.0,38690,130.0,136.0,"7,6",NaN
430,There Be Dragons,2011.0,Biography|Drama|War,English,Spain,PG-13,102.0,"2,35",36000000.0,1068392.0,...,794.0,785.0,3497,2000,0.0,3865,53.0,77.0,"5,9",NaN
438,War Horse,2011.0,Drama|War,English,USA,PG-13,146.0,"2,35",66000000.0,79883359.0,...,19000.0,979.0,46726,28000,1.0,116159,488.0,388.0,"7,2",NaN
460,Act of Valor,2012.0,Action|Adventure|Drama|Thriller|War,English,USA,R,110.0,"2,35",12000000.0,70011073.0,...,17.0,11.0,146,15000,0.0,57996,349.0,216.0,"6,5",NaN
511,For Greater Glory: The True Story of Cristiada,2012.0,Drama|History|War,Spanish,Mexico,R,145.0,"2,35",10818775.0,5669081.0,...,377.0,280.0,1807,0,1.0,3665,57.0,43.0,"6,6",NaN
542,Lincoln,2012.0,Biography|Drama|History|War,English,USA,PG-13,150.0,"2,35",65000000.0,182204440.0,...,826.0,655.0,25517,71000,0.0,197412,720.0,538.0,"7,4",NaN
572,Red Tails,2012.0,Action|Adventure|Drama|History|War,English,USA,PG-13,125.0,"2,35",58000000.0,49875589.0,...,664.0,519.0,4416,0,0.0,28807,273.0,144.0,"5,9",NaN
724,"Cinco de Mayo, La Batalla",2013.0,Drama|History|War,Spanish,Mexico,R,125.0,NaN,10000000.0,169379.0,...,61.0,36.0,221,874,1.0,683,3.0,12.0,"6,2",NaN
784,Lone Survivor,2013.0,Action|Biography|Drama|Thriller|War,English,USA,R,121.0,"2,35",40000000.0,125069696.0,...,449.0,127.0,1261,58000,0.0,203963,420.0,319.0,"7,6",NaN
844,The Book Thief,2013.0,Drama|War,English,USA,PG-13,131.0,"2,35",19000000.0,21483154.0,...,526.0,326.0,1985,53000,1.0,98741,236.0,252.0,"7,6",NaN
880,The Railway Man,2013.0,Biography|Drama|Romance|War,English,Australia,R,116.0,"2,35",18000000.0,4435083.0,...,14000.0,212.0,39463,18000,2.0,27882,119.0,186.0,"7,1",NaN
915,300: Rise of an Empire,2014.0,Action|Drama|Fantasy|War,English,USA,R,102.0,"2,35",110000000.0,106369117.0,...,1000.0,1000.0,10583,71000,0.0,225273,523.0,366.0,"6,2",NaN
931,American Sniper,2014.0,Action|Biography|Drama|History|Thriller|War,English,USA,R,133.0,"2,35",58800000.0,350123553.0,...,962.0,318.0,16277,112000,0.0,325264,916.0,490.0,"7,3",NaN
952,Born of War,2014.0,Action|Drama|Thriller|War,English,UK,R,109.0,NaN,5000000.0,NaN,...,266.0,126.0,1681,190,3.0,237,3.0,8.0,"4,4",NaN
971,Dracula Untold,2014.0,Action|Drama|Fantasy|Horror|War,English,USA,PG-13,92.0,"2,35",70000000.0,55942830.0,...,692.0,423.0,5178,37000,1.0,138582,423.0,261.0,"6,3",NaN
987,Far from Men,2014.0,Drama|War|Western,French,France,NaN,101.0,"2,35",7700000.0,NaN,...,154.0,40.0,10218,2000,0.0,4035,19.0,102.0,"7,3",NaN
991,Fury,2014.0,Action|Drama|War,English,USA,R,134.0,"2,35",68000000.0,85707116.0,...,8000.0,697.0,20411,82000,4.0,303185,701.0,406.0,"7,6",NaN
1115,The Imitation Game,2014.0,Biography|Drama|Thriller|War,English,UK,PG-13,114.0,"2,35",14000000.0,91121452.0,...,393.0,305.0,20295,165000,1.0,467613,608.0,454.0,"8,1",NaN
1122,The Monuments Men,2014.0,Drama|War,English,USA,PG-13,118.0,"2,35",70000000.0,78031620.0,...,13000.0,559.0,27674,34000,7.0,102248,403.0,371.0,"6,1",NaN
1138,The Water Diviner,2014.0,Drama|War,English,Australia,R,111.0,"2,35",22500000.0,4190530.0,...,468.0,234.0,1795,18000,0.0,53341,185.0,183.0,"7,1",NaN
1149,Unbroken,2014.0,Biography|Drama|Sport|War,English,USA,PG-13,137.0,"2,35",65000000.0,115603980.0,...,698.0,465.0,2938,35000,0.0,103589,351.0,322.0,"7,2",NaN
1150,Unbroken,2014.0,Biography|Drama|Sport|War,English,USA,PG-13,137.0,"2,35",65000000.0,115603980.0,...,698.0,465.0,2938,35000,0.0,103589,351.0,322.0,"7,2",NaN
1185,Baahubali: The Beginning,2015.0,Action|Adventure|Drama|Fantasy|War,Telugu,India,NaN,159.0,"1,85",18026148.0,6498000.0,...,133.0,72.0,554,21000,1.0,62756,410.0,44.0,"8,4",NaN
1267,Little Boy,2015.0,Drama|War,English,Mexico,PG-13,106.0,"2,35",20000000.0,6420319.0,...,1000.0,975.0,5705,15000,0.0,15978,122.0,45.0,"7,4",NaN
1392,13 Hours,2016.0,Action|Drama|Thriller|War,English,USA,R,144.0,"2,35",50000000.0,52822418.0,...,726.0,681.0,3580,44000,0.0,47764,219.0,204.0,"7,4",NaN
1394,Airlift,2016.0,Action|Drama|History|Thriller|War,Hindi,India,NaN,130.0,"2,35",4400000.0,NaN,...,26.0,12.0,151,10000,1.0,30977,178.0,39.0,"8,5",NaN
1419,Free State of Jones,2016.0,Action|Biography|Drama|History|War,English,USA,R,139.0,"1,85",50000000.0,20389967.0,...,552.0,303.0,12786,10000,1.0,3077,47.0,79.0,"6,7",NaN
1451,Operation Chromite,2016.0,Action|Drama|History|War,English,South Korea,NaN,115.0,NaN,12620000.0,31662.0,...,81.0,29.0,14133,139,1.0,90,1.0,2.0,"6,8",NaN
1514,Deadline Gallipoli,NaN,Drama|War,English,Australia,NaN,197.0,NaN,15000000.0,NaN,...,476.0,110.0,1400,367,0.0,299,1.0,NaN,"7,4",NaN
1544,M*A*S*H,NaN,Comedy|Drama|War,English,USA,TV-PG,25.0,4,NaN,NaN,...,421.0,395.0,2195,0,5.0,36265,147.0,55.0,"8,4",NaN
1599,War & Peace,NaN,Drama|History|Romance|War,English,UK,TV-14,NaN,16,NaN,NaN,...,888.0,502.0,4528,11000,1.0,9277,44.0,10.0,"8,2",NaN

In [ ]:
# 6. visualizzare i film fantasy e i thriller
ilfile[(ilfile["Genres"].str.contains("Fantasy")) | (ilfile["Genres"].str.contains("Thriller"))]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
0,127 Hours,2010.0,Adventure|Biography|Drama|Thriller,English,USA,R,94.0,"1,85",18000000.0,18329466.0,...,642.0,223.0,11984,63000,0.0,279179,440.0,450.0,"7,6",NaN
5,Alice in Wonderland,2010.0,Adventure|Family|Fantasy,English,USA,PG,108.0,"1,85",200000000.0,334185206.0,...,25000.0,11000.0,79957,24000,0.0,306320,736.0,451.0,"6,5",NaN
6,Alice in Wonderland,2010.0,Adventure|Family|Fantasy,English,USA,PG,108.0,"1,85",200000000.0,334185206.0,...,25000.0,11000.0,79957,24000,0.0,306336,736.0,451.0,"6,5",NaN
7,All Good Things,2010.0,Crime|Drama|Mystery|Romance|Thriller,English,USA,R,101.0,"1,85",NaN,578382.0,...,4000.0,902.0,39515,0,2.0,41249,67.0,140.0,"6,3",NaN
17,Beyond the Black Rainbow,2010.0,Sci-Fi|Thriller,English,Canada,R,110.0,"2,35",1100000.0,56129.0,...,95.0,48.0,645,0,1.0,6555,82.0,97.0,"6,1",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,The Secret,NaN,Drama|Thriller,English,UK,NaN,45.0,NaN,NaN,NaN,...,133.0,119.0,1393,405,3.0,653,4.0,1.0,"7,3",NaN
1594,Trapped,NaN,Crime|Drama|Thriller,Icelandic,Iceland,NaN,511.0,16,NaN,NaN,...,63.0,51.0,307,0,0.0,2308,19.0,16.0,"8,2",NaN
1595,Twisted,NaN,Drama|Mystery|Thriller,English,USA,NaN,60.0,16,NaN,NaN,...,512.0,398.0,2758,915,2.0,7945,22.0,4.0,"7,5",NaN
1601,Wolf Creek,NaN,Drama|Horror|Thriller,English,Australia,NaN,NaN,2,NaN,NaN,...,457.0,206.0,1617,954,0.0,726,6.0,2.0,"7,1",NaN
1603,Yu-Gi-Oh! Duel Monsters,NaN,Action|Adventure|Animation|Family|Fantasy,Japanese,Japan,NaN,24.0,NaN,NaN,NaN,...,NaN,NaN,0,124,0.0,12417,51.0,6.0,7,NaN

In [ ]:
# 9. visualizzare i titoli dei film di cui non si conosce il budget
ilfile[ilfile["Budget"].isna()]["Title"]

In [ ]:
# 10. visualizzare i titoli dei film e il relativo regista. Ordinare a partire dal film che ha il budget più alto

ilfile.sort_values(by=["Budget"], ascending=False)
ilfile[["Title", "Director"]]

In [ ]:
# 11. visualizzare i titoli dei film che hanno incassato più di quanto è stato speso per realizzarli
# Budget;Gross Earnings
ilfile[ilfile["Gross Earnings"] > ilfile["Budget"]]["Title"]

0                      127 Hours
5            Alice in Wonderland
6            Alice in Wonderland
8                Alpha and Omega
15                     Beginners
                  ...
1477             The Jungle Book
1483           The Perfect Match
1484    The Purge: Election Year
1485     The Secret Life of Pets
1486                The Shallows
Name: Title, Length: 548, dtype: object